routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'HomeController@index');

Route::resource('photos', 'PhotoController')->only('store');
Route::post('photos/search-by-tag', 'PhotoController@searchByTag')->name('photos.search-by-tag');
Route::patch('photos/{photo}/add-tag/', 'PhotoController@addTag')->name('photos.add-tag');
Route::patch('photos/{photo}/remove-tag/{tag}', 'PhotoController@removeTag')->name('photos.remove-tag');

Route::resource('tags', 'TagController')->only('store', 'update', 'destroy');

app/Models/Photo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $fillable = ['path'];

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public static function searchByTag($searchString)
    {
        return static::whereHas('tags', function ($query) use ($searchString) {
            $query->where('keyword', 'like', '%'.$searchString.'%');
        })->get();
    }
}

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['keyword'];

    public $timestamps = false;

    public function photos()
    {
        return $this->belongsToMany(Photo::class);
    }
}

app/Models/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Photo;
use App\Models\Tag;

class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $photos = Photo::with('tags')->get();

        return view('home', compact('photos'));
    }
}

app/Http/Controllers/PhotoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Photo;
use App\Models\Tag;

use App\Repositories\TagRepository;
use App\Repositories\PhotoRepository;

class PhotoController extends Controller
{

    public function store(Request $request)
    {
        $request->validate([
            'photo' => 'required|image',
            'tags'  => 'required'
        ]);

        $photo = PhotoRepository::storeAndCreate($request->file('photo'));
        $tags  = TagRepository::createAndCheck($request->get('tags'));

        $photo->tags()->attach($tags);

        return back();
    }

    public function addTag(Request $request, Photo $photo)
    {
        $tags = TagRepository::createAndCheck($request->get('tags'));

        $photo->tags()->attach($tags);

        return back();
    }

    public function removeTag(Photo $photo, Tag $tag)
    {
        $photo->tags()->detach($tag);

        return back();
    }

    public function searchByTag(Request $request)
    {
        $photos = Photo::searchByTag($request->get('search'));

        return back()->with('photos', $photos);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Tag;

class TagController extends Controller
{

    public function update(Request $request, Tag $tag)
    {
        $tag->update([
            'keyword' => $request->get('keyword')
        ]);

        return back();
    }

    public function destroy(Tag $tag)
    {
        $tag->delete();

        return back();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form action="{{ route('photos.store') }}" method="post" enctype="multipart/form-data">
                    {{ csrf_field() }}

                    <div class="form-group">
                        <label for="">Upload Image:</label>
                        <input type="file" class="form-control-file" name="photo" >
                    </div>

                    <div class="form-group">
                        <label for="tags">Add Tags to image:</label>
                        <small>Separated by comma</small>

                        <input type="text" class="form-control" name="tags" id="tags" value="{{ old('tags') }}">
                    </div>
                    
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>

                <br>

                @include('partials.errors')
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-md-12">
                <form action="{{ route('photos.search-by-tag') }}" method="post">
                    {{ csrf_field() }}
                    
                    <div class="form-group">
                        <label for="">Search by tag:</label>
                        <input type="text" class="form-control" name="search">
                    </div>

                    <button class="btn btn-primary" type="submit">Search</button>
                </form>
            </div>
        </div>

        <div class="row mt-3">
            @if (session()->has('photos'))
                @foreach (session('photos') as $photo)
                    <div class="col-md-3">
                        <img src="{{ Storage::url($photo->path) }}" class="img-fluid" style="width: 100%" alt="">

                        @foreach ($photo->tags as $tag)
                            <span class="badge badge-secondary">
                                {{ $tag->keyword }}
                                <form action="{{ route('photos.remove-tag', [$photo->id, $tag->id]) }}" method="post">
                                    {{ method_field('PATCH') }}
                                    {{ csrf_field() }}

                                    <button type="submit" class="btn btn-secondary">X</button>
                                </form>
                            </span>
                        @endforeach

                        <form action="{{ route('photos.add-tag', $photo->id) }}" method="post">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="tags">Add Tags to image:</label>
                                <small>Separated by comma</small>
                                
                                <input type="text" class="form-control" name="tags" id="tags" value="{{ old('tags') }}">
                            </div>

                            <button class="btn btn-primary" type="submit">Add</button>
                        </form>
                    </div>
                @endforeach
            @else
                @foreach ($photos as $photo)
                    <div class="col-md-3">
                        <img src="{{ Storage::url($photo->path) }}" class="img-fluid" style="width: 100%" alt="">

                        @foreach ($photo->tags as $tag)
                            <span class="badge badge-secondary">
                                {{ $tag->keyword }}
                                <form action="{{ route('photos.remove-tag', [$photo->id, $tag->id]) }}" method="post">
                                    {{ method_field('PATCH') }}
                                    {{ csrf_field() }}

                                    <button type="submit" class="btn btn-secondary">X</button>
                                </form>
                            </span>
                        @endforeach

                        <form action="{{ route('photos.add-tag', $photo->id) }}" method="post">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="tags">Add Tags to image:</label>
                                <small>Separated by comma</small>
                                
                                <input type="text" class="form-control" name="tags" id="tags" value="{{ old('tags') }}">
                            </div>

                            <button class="btn btn-primary" type="submit">Add</button>
                        </form>
                    </div>
                @endforeach
            @endif
        </div>
    </div>
@endsection

@push('scripts')
    <script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/js/bootstrap-editable.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.tags-editable').editable();
        });
    </script>
@endpush

@push('styles')
    <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/jquery-editable/css/jquery-editable.css" rel="stylesheet"/>
@endpush

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    @stack('styles')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    @stack('scripts')
</body>
</html>

resources/views/partials/errors.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif